on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - develop

name: "Build & Release"
jobs:
  build:
    name: Build, Test & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      # Run Flutter tests
      - name: Run Flutter Tests
        run: flutter test
        continue-on-error: true

      # Build App Bundle (AAB) for Android
      - name: Build Android App Bundle
        run: flutter build appbundle --release --verbose

      # Optional: Build iOS
      # Uncomment and add steps for iOS if needed (MacOS runner is required for iOS)

      # Push to Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/bundle/release/*.aab, # AAB for Android
            build/ios/iphoneos/app.ipa              # IPA for iOS (if applicable)
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
